website/views.py
import os
from urllib.parse import urlparse

import subprocess
from flask import current_app

import pytz
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, flash, send_file
from werkzeug.utils import secure_filename

from .models import Medicament, Demande, Commande, Archive, Commande_article, Archive_article, Article, Demande_article
from .database import db
from datetime import datetime, timedelta
from dateutil import tz

from .upload import UploadForm

main = Blueprint('main', __name__)

algeria_tz = tz.gettz('Africa/Algiers')

@main.route('/')
def index():
    demandes = Demande.query.order_by(Demande.date_demande.desc()).all()
    return render_template('index.html',pytz=pytz, algeria_tz=algeria_tz, active_page ='home',demandes=demandes)

@main.route('/search_medicaments', methods=['GET'])
def search_medicaments():
    search = request.args.get('search')
    medicaments = Medicament.query.filter(Medicament.nom.like(f'%{search}%')).all()
    return jsonify([medicament.nom for medicament in medicaments])

@main.route('/add_demande', methods=['POST'])
def add_demande():
    medicament_name = request.form.get('medicament')
    quantity = int(request.form.get('quantity_needed'), 0)
    confirm_order = request.form.get('confirm_order')

    if not medicament_name:
        return "Error: Medicament name is required", 400

    if not quantity:
        return "Error: Quantity is required", 400

    medicament = Medicament.query.filter_by(nom=medicament_name).first()

    if not medicament:
        medicament = Medicament(nom=medicament_name)
        db.session.add(medicament)
        db.session.commit()

    # Check if a demande for the same medicament has been made in the last 24 hours
    one_day_ago = datetime.utcnow() - timedelta(days=1)
    recent_demande = Demande.query.filter_by(medicament_id=medicament.id).filter(Demande.date_demande >= one_day_ago).first()

    if recent_demande and not confirm_order:
        return jsonify({
                           "error": f"{recent_demande.quantite_demandee} {medicament_name} ont déjà été demander le : {recent_demande.date_demande.strftime('%d/%m/%Y')}"}), 409

    if recent_demande and confirm_order:
        # If the user confirmed the order, add the new quantity to the existing demande and update the date
        recent_demande.quantite_demandee += quantity
        recent_demande.date_demande = datetime.utcnow()
    else:
        # If there is no recent demande, create a new one
        demande = Demande(medicament_id=medicament.id, quantite_demandee=quantity)
        db.session.add(demande)
        db.session.commit()  # Commit the Demande to the database here

        # Create a new Commande for the new Demande
        commande = Commande(demande_id=demande.id)
        db.session.add(commande)

    db.session.commit()

    # Get the referrer URL
    referrer = request.referrer
    if referrer:
        # Parse the URL to get only the path
        referrer_path = urlparse(referrer).path
        # Redirect to the referrer page
        return redirect(referrer_path)
    else:
        # If there is no referrer, redirect to 'index' as default
        return redirect(url_for('main.index'))

@main.route('/commande')
def commande():
    commandes = Commande.query.all()
    return render_template('indexcommande.html', pytz=pytz, algeria_tz=algeria_tz,commandes=commandes, active_page='commande')

@main.route('/archive_commande/<int:commande_id>', methods=['POST'])
def archive_commande(commande_id):
    fournisseur = request.form.get('fournisseur')
    quantite = int(request.form.get('quantite')) if fournisseur != "MANQUANT" else 0
    observation = request.form.get('observation')

    commande = Commande.query.get(commande_id)
    if commande:
        if fournisseur != "MANQUANT":
            # Créer une nouvelle archive
            archive = Archive(
                medicament_id=commande.demande.medicament_id,
                quantite_demandee_archive=commande.demande.quantite_demandee,
                date_demande_archive=commande.demande.date_demande,
                quantite_commandee_archive=quantite,
                fournisseur_archive=fournisseur,
                date_commande_archive=datetime.utcnow(),
                observation=observation
            )
            db.session.add(archive)
        else:
            # Si le fournisseur est "MANQUANT", mettre à jour le fournisseur dans la table Commande
            commande.fournisseur = "MANQUANT"

        # Vérifier si la quantité commandée est inférieure à la quantité demandée
        if quantite < commande.demande.quantite_demandee:
            # Si c'est le cas, mettre à jour la quantité demandée avec la quantité restante
            commande.demande.quantite_demandee -= quantite
        elif fournisseur != "MANQUANT":
            # Sinon, supprimer la demande
            db.session.delete(commande.demande)

        db.session.commit()
        return "Commande mise à jour ou supprimée", 200
    else:
        return "Erreur : Commande non trouvée", 404

@main.route('/delete_demande/<int:demande_id>', methods=['GET'])
def delete_demande(demande_id):
    demande = Demande.query.get(demande_id)
    if demande:
        db.session.delete(demande)
        db.session.commit()
        return redirect(url_for('main.index'))
    else:
        return "Error: Record not found", 404


@main.route('/modifier_demande/<int:demande_id>', methods=['POST'])
def modifier_demande(demande_id):
    demande = Demande.query.get(demande_id)
    if demande:
        new_quantity = int(request.form.get('new_quantity'))
        demande.quantite_demandee = new_quantity
        db.session.commit()
        flash('La demande a été modifiée avec succès.', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('Erreur : Demande non trouvée', 'error')
        return redirect(url_for('main.index'))


@main.route('/archive')
def archive():
    archives = Archive.query.all()
    return render_template('indexarchive.html', pytz=pytz, algeria_tz=algeria_tz,archives=archives, active_page='archive')

@main.route('/delete_archive', methods=['POST'])
def delete_archive():
    archive_ids = request.form.getlist('archive_ids')
    for archive_id in archive_ids:
        archive = Archive.query.get(archive_id)
        if archive:
            db.session.delete(archive)
    db.session.commit()
    return redirect(url_for('main.archive'))


@main.route('/modifier_archive/<int:archive_id>', methods=['POST'])
def modifier_archive(archive_id):
    archive = Archive.query.get(archive_id)
    if archive:
        new_quantity = int(request.form.get('new_quantity'))
        archive.quantite_commandee_archive = new_quantity
        db.session.commit()
        flash('L\'archive a été modifiée avec succès.', 'success')
        return redirect(url_for('main.archive'))
    else:
        flash('Erreur : Archive non trouvée', 'error')
        return redirect(url_for('main.archive'))




# Cotee article

@main.route('/article')
def article():
    demandes = Demande_article.query.order_by(Demande_article.date_demande.desc()).all()
    return render_template('indexarticle.html', pytz=pytz, algeria_tz=algeria_tz,demandes=demandes, active_page='article')

@main.route('/search_articles', methods=['GET'])
def search_articles():
    search = request.args.get('search')
    articles = Article.query.filter(Article.nom.like(f'%{search}%')).all()
    return jsonify([article.nom for article in articles])


@main.route('/add_demande_article', methods=['POST'])
def add_demande_article():
    article_name = request.form.get('article')
    quantity = int(request.form.get('quantity_needed_article') or 0)
    confirm_order = request.form.get('confirm_order')

    if not article_name:
        return "Error: Article name is required", 400

    if quantity is None:
        return "Error: Quantity is required", 400

    article = Article.query.filter_by(nom=article_name).first()

    if not article:
        article = Article(nom=article_name)
        db.session.add(article)
        db.session.commit()

    demande = Demande_article(article_id=article.id, quantite_demandee=quantity)
    db.session.add(demande)
    db.session.commit()

    commande = Commande_article(demande_article_id=demande.id)
    db.session.add(commande)
    db.session.commit()

    referrer = request.referrer
    if referrer:
        referrer_path = urlparse(referrer).path
        return redirect(referrer_path)
    else:
        return redirect(url_for('main.article'))


@main.route('/commande_article')
def commande_article():
    commandes = Commande_article.query.all()
    return render_template('indexcommandearticle.html', pytz=pytz, algeria_tz=algeria_tz,commandes=commandes, active_page='commande_article')

@main.route('/archive_commande_article/<int:commande_article_id>', methods=['POST'])
def archive_commande_article(commande_article_id):
    fournisseur = request.form.get('fournisseur')
    quantite = int(request.form.get('quantite'))
    observation = request.form.get('observation')

    commande = Commande_article.query.get(commande_article_id)
    if commande:
        archive = Archive_article(
            article_id=commande.demande_article.article_id,
            quantite_demandee_archive=commande.demande_article.quantite_demandee,
            date_demande_archive=commande.demande_article.date_demande,
            quantite_commandee_archive=quantite,
            fournisseur_archive=fournisseur,
            date_commande_archive=datetime.utcnow(),
            observation=observation
        )
        db.session.add(archive)
        if quantite < commande.demande_article.quantite_demandee:
            commande.demande_article.quantite_demandee -= quantite
        else:
            db.session.delete(commande.demande_article)
        db.session.commit()
        return "Commande archivée et demande supprimée", 200
    else:

website/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pharmacie Abdelkrim</title>
    <link rel="shortcut icon" href="../static/img/svg/logo.svg" type="image/x-icon">
    <link rel="stylesheet" href="../static/css/style.min.css">
    <style>

  </style>
</head>

<body>
<div class="layer"></div>
<!-- ! Body -->
<div class="page-flex">
  <!-- ! Sidebar -->
  <aside class="sidebar">
    <div class="sidebar-start">
        <div class="sidebar-head">
            <a href="/" class="logo-wrapper" title="Home">
                <span class="sr-only">Home</span>
                <span class="icon logo" aria-hidden="true"></span>
                <div class="logo-text">
                    <span class="logo-title">Pharmacie</span>
                    <span class="logo-subtitle">Abdelkrim</span>
                </div>
            </a>
        </div>
        <div class="sidebar-body">
            <ul class="sidebar-body-menu">
                <li>
                    <a class="show-cat-btn">
                        <span class="icon document" aria-hidden="true"></span>Pharmacetique
                        <span class="category__btn transparent-btn" title="Open list">
                            <span class="sr-only">Open list</span>
                            <span class="icon arrow-down" aria-hidden="true"></span>
                        </span>
                    </a>
                    <ul class="cat-sub-menu">
                        <li><a href="/" class="{{ 'active' if active_page == 'home' else '' }}">A commander</a></li>
                        <li><a href="/commande"  class="{{ 'active' if active_page == 'commande' else '' }}">Panier</a></li>
                        <li><a href="/archive" class="{{ 'active' if active_page == 'archive' else '' }}">Archives</a></li>
                    </ul>
                </li>
                <li>
                  <a class="show-cat-btn" href="##" >
                      <span class="icon folder" aria-hidden="true"></span>ParaPharmacetique
                      <span class="category__btn transparent-btn" title="Open list">
                          <span class="sr-only">Open list</span>
                          <span class="icon arrow-down" aria-hidden="true"></span>
                      </span>
                  </a>
                  <ul class="cat-sub-menu">
                        <li><a href="/article" class="{{ 'active' if active_page == 'article' else '' }}">A commander</a></li>
                        <li><a href="/commande_article" class="{{ 'active' if active_page == 'commande_article' else '' }}">Panier</a></li>
                        <li><a href="/archive_article" class="{{ 'active' if active_page == 'archive_article' else '' }}">Archives</a></li>
                  </ul>
              </li>
{#              <span class="system-menu__title">Autres</span>#}
                <li>
                  <a class="show-cat-btn" href="##" >
                      <span class="icon paper" aria-hidden="true"></span>Autres
                      <span class="category__btn transparent-btn" title="Open list">
                          <span class="sr-only">Open list</span>
                          <span class="icon arrow-down" aria-hidden="true"></span>
                      </span>
                  </a>
                  <ul class="cat-sub-menu">
                        <li><a href="/gardes" class="{{ 'active' if active_page == 'gardes' else '' }}">Gardes</a></li>
                        <li><a href="/update" class="{{ 'active' if active_page == 'update' else '' }}">Update</a></li>
                  </ul>

              </li>
            </ul>
        </div>
    </div>
  </aside>
<div class="main-wrapper">
{% block nav %}{% endblock %}

{% block content %}{% endblock %}
    <footer class="footer">
      <div class="container footer--flex">
        <div class="footer-start">
          <p>2024 © BABIBORIS - </p>
        </div>
      </div>
    </footer>
</div>
</div>
<script>
document.getElementById('RechercheFiltrer').addEventListener('keyup', function() {
  let searchQuery = this.value.toLowerCase();
  let tableRows = document.querySelectorAll('.posts-table tbody tr');

  tableRows.forEach(row => {
    let cells = Array.from(row.querySelectorAll('td'));
    let rowContainsQuery = cells.some(cell => cell.textContent.toLowerCase().includes(searchQuery));
    row.style.display = rowContainsQuery ? "" : "none";
  });
});
</script>
<!-- Chart library -->
<script src="../static/plugins/chart.min.js"></script>
<!-- Icons library -->
<script src="../static/plugins/feather.min.js"></script>
<!-- Custom scripts -->
<script src="../static/js/script.js"></script>
    <script>
document.getElementById('select-all').addEventListener('change', function(e) {
    var checkboxes = document.getElementsByClassName('select-item');
    for (var i = 0; i < checkboxes.length; i++) {
        checkboxes[i].checked = e.target.checked;
    }
});
    </script>
</body>

</html>

website/templates/gardes.html
{% extends "base.html" %}
{% block content %}
    <main class="main users chart-page" id="skip-target">
      <div class="container">
        <h2 class="main-title">Listes des pharmacies de garde : </h2>
        <div class="row">
          <div class="col-lg-12">
            <div class="users-table table-wrapper">
            <div class="users-table table-wrapper">
              <table class="posts-table">
                <thead>
                  <tr class="users-table-info">
                    <th style="padding-left: 10px;">Date</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for garde in gardes %}
                      <tr style="color : white">
                        <td>{{ garde }}</td>
                        <td>
                            <a href="{{ url_for('main.download_garde', date=garde) }}">
                                <img src="{{ url_for('static', filename='img/svg/dl.svg') }}" alt="Télécharger">
                            </a>
                        </td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}
{% block nav %}
<nav class="main-nav--bg">
<div class="container main-nav">
  <div class="main-nav-start">
      <form action="/add_demande" method="post" class="d-flex">
        <div class="search-wrapper">
          <i data-feather="search" aria-hidden="true"></i>
          <input type="search" name="medicament" list="medicaments" id="medicament" placeholder="Nom du médicament..." required autofocus>
            <datalist id="medicaments"></datalist>
        </div>
        <div class="search-wrapper">
          <input class="form-control me-2" type="number" id="quantity_needed" min="1" placeholder="Quantité" name ="quantity_needed" style="width: 150px; margin-top: 10px;" required>
          <button class="button-12" type="submit">Ajouter</button>
        </div>
      </form>
  </div>
</div>
</nav>
{% endblock %}
{% block content %}
    <main class="main users chart-page" id="skip-target">
      <div class="container">
        <h2 class="main-title">Vos demandes de médicaments :</h2>
        <div class="row">
          <div class="col-lg-12">
            <div class="users-table table-wrapper">
            <div class="search-wrapper" style="display: flex; justify-content: center; align-items: center; padding-bottom: 10px">
              <input type="text" id="RechercheFiltrer" placeholder="Que voulez-vous chercher ?">
            </div>
            <div class="users-table table-wrapper">
              <table class="posts-table">
                <thead>
                  <tr class="users-table-info">
                    <th style="padding-left: 10px;">Date</th>
                    <th>Nom du médicament</th>
                    <th>Quantité demandée</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                {% for demande in demandes %}
                  <tr style="color : white">
                        <td>{{ demande.date_demande.replace(tzinfo=pytz.utc).astimezone(algeria_tz).strftime('%d/%m/%Y %H:%M:%S') }}</td>
                      <td>{{ demande.medicament.nom }}</td>
                    <td>{{ demande.quantite_demandee }}</td>
                    <td>
                      <span class="p-relative">
                        <button class="dropdown-btn transparent-btn" type="button" title="More info">
                          <div class="sr-only">More info</div>
                          <i data-feather="more-horizontal" aria-hidden="true"></i>
                        </button>
                        <ul class="users-item-dropdown dropdown">
                          <li><a href="{{ url_for('main.delete_demande', demande_id=demande.id) }}">Supprimer</a></li>
                        </ul>
                      </span>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

website/templates/indexarchive.html
{% extends "base.html" %}
{% block content %}
    <main class="main users chart-page" id="skip-target">
      <div class="container">
        <h2 class="main-title">Archives de vos commandes de médicaments :</h2>
        <div class="row">
          <div class="col-lg-12">
            <div class="users-table table-wrapper">
            <div class="search-wrapper" style="display: flex; justify-content: center; align-items: center; padding-bottom: 10px">
              <input type="text" id="RechercheFiltrer" placeholder="Que voulez-vous chercher ?">
            </div>
            <div class="users-table table-wrapper">
            <form action="{{ url_for('main.delete_archive') }}" method="post">
                <div class="search-wrapper" style="display: flex; justify-content: left; align-items: center; padding-bottom: 10px">
                  <button class="button-12" type="submit">Supprimer la sélection</button>
                </div>
                <table class="posts-table">
                <thead>
                  <tr class="users-table-info">
                    <th style="padding-left: 21px;"><input type="checkbox" id="select-all"></th>
                    <th style="padding-left: 10px;">Date</th>
                    <th>Nom du médicament</th>
                    <th>Quantité </th>
                    <th>Fournisseur</th>
                    <th>Observation</th>
                    <th>Demander le</th>
                    <th>Quantité demander</th>
                  </tr>
                </thead>
                <tbody>
                {% for archive in archives|sort(attribute='date_archive', reverse=True) %}
                  <tr style="color : white">
                    <td>
                      <input type="checkbox" name="archive_ids" value="{{ archive.id }}" class="select-item">
                    </td>
                    <td>{{ archive.date_archive.replace(tzinfo=pytz.utc).astimezone(algeria_tz).strftime('%d/%m/%Y %H:%M:%S') }}</td>
                    <td>{{ archive.medicament.nom }}</td>
                    <td>{{ archive.quantite_commandee_archive }}</td>
                    <td>{{ archive.fournisseur_archive }}</td>
                    <td>{{ archive.observation }}</td>
                    <td>{{ archive.date_demande_archive.replace(tzinfo=pytz.utc).astimezone(algeria_tz).strftime('%d/%m/%Y %H:%M:%S') }}</td>
                    <td>{{ archive.quantite_demandee_archive }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
             </form>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

website/templates/indexarchivearticle.html
{% extends "base.html" %}
{% block content %}
    <main class="main users chart-page" id="skip-target">
      <div class="container">
        <h2 class="main-title">Archives de vos commandes d'articles :</h2>
        <div class="row">
          <div class="col-lg-12">
            <div class="users-table table-wrapper">
            <div class="search-wrapper" style="display: flex; justify-content: center; align-items: center; padding-bottom: 10px">
              <input type="text" id="RechercheFiltrer" placeholder="Que voulez-vous chercher ?">
            </div>
            <form action="{{ url_for('main.delete_archive_articles') }}" method="post">
            <div class="search-wrapper" style="display: flex; justify-content: left; align-items: center; padding-bottom: 10px">
              <button class="button-12" type="submit">Supprimer la sélection</button>
            </div>
              <table class="posts-table">
                <thead>
                  <tr class="users-table-info">
                    <th style="padding-left: 21px;"><input type="checkbox" id="select-all"></th>
                    <th>Commander le </th>
                    <th>Nom de l'article</th>
                    <th>Quantité </th>
                    <th>Fournisseur</th>
                    <th>Observation</th>
                    <th>Demander le</th>
                    <th>Quantité demander</th>
                  </tr>
                </thead>
                <tbody>
                {% for archive_article in archives|sort(attribute='date_archive', reverse=True) %}
                  <tr style="color : white">
                    <td>
                      <input type="checkbox" name="archive_article_ids" value="{{ archive_article.id }}" class="select-item">
                    </td>
                    <td>{{ archive_article.date_archive.replace(tzinfo=pytz.utc).astimezone(algeria_tz).strftime('%d/%m/%Y %H:%M:%S') }}</td>
                    <td>{{ archive_article.article.nom }}</td>
                    <td>{{ archive_article.quantite_commandee_archive }}</td>
                    <td>{{ archive_article.fournisseur_archive }}</td>
                    <td>{{ archive_article.observation }}</td>
                    <td>{{ archive_article.date_demande_archive.replace(tzinfo=pytz.utc).astimezone(algeria_tz).strftime('%d/%m/%Y %H:%M:%S') }}</td>
                    <td>{{ archive_article.quantite_demandee_archive }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </form>
            </div>
          </div>
        </div>
      </div>
    </main>


{% endblock %}

website/templates/indexarticle.html
{% extends "base.html" %}
{% block nav %}
<nav class="main-nav--bg">
<div class="container main-nav">
  <div class="main-nav-start">
      <form action="/add_demande_article" method="post" class="d-flex">
        <div class="search-wrapper">
          <i data-feather="search" aria-hidden="true"></i>
          <input type="search" name="article" list="articles" id="search-article" placeholder="Nom de l'article..." required autofocus>
            <datalist id="articles"></datalist>
        </div>
        <div class="search-wrapper">
          <input class="form-control me-2" type="number" id="quantity_needed_article" min="1" placeholder="Quantité" name ="quantity_needed_article" style="width: 150px; margin-top: 10px;" required>
          <button class="button-12" type="submit">Ajouter</button>
        </div>
      </form>
  </div>
</div>
</nav>
{% endblock %}
{% block content %}
    <main class="main users chart-page" id="skip-target">
      <div class="container">
        <h2 class="main-title">Vos demandes d'articles :</h2>
        <div class="row">
          <div class="col-lg-12">
            <div class="users-table table-wrapper">
            <div class="search-wrapper" style="display: flex; justify-content: center; align-items: center; padding-bottom: 10px">
              <input type="text" id="RechercheFiltrer" placeholder="Que voulez-vous chercher ?">
            </div>
            <div class="users-table table-wrapper">
              <table class="posts-table">
                <thead>
                  <tr class="users-table-info">
                    <th style="padding-left: 10px;">Date</th>
                    <th>Nom de l'article</th>
                    <th>Quantité demandée</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                {% for demande_article in demandes %}
                  <tr style="color : white">
                    <td>{{ demande_article.date_demande.replace(tzinfo=pytz.utc).astimezone(algeria_tz).strftime('%d/%m/%Y %H:%M:%S') }}</td>
                    <td>{{ demande_article.article.nom }}</td>
                    <td>{{ demande_article.quantite_demandee }}</td>
                    <td>
                      <span class="p-relative">
                        <button class="dropdown-btn transparent-btn" type="button" title="More info">
                          <div class="sr-only">More info</div>
                          <i data-feather="more-horizontal" aria-hidden="true"></i>
                        </button>
                        <ul class="users-item-dropdown dropdown">
                          <li><a href="{{ url_for('main.delete_demande_article', demande_article_id=demande_article.id) }}">Supprimer</a></li>
                        </ul>
                      </span>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>

{% endblock %}

website/templates/update.html
{% extends "base.html" %}
{% block content %}
    <main class="main users chart-page" id="skip-target">
      <div class="container">
        <h2 class="main-title">Upload un fichier .mdb (Access 2003) </h2>
        <div class="row">
          <div class="col-lg-12">
            <form action="{{ url_for('main.upload') }}" method="POST" enctype="multipart/form-data">
              {{ form.hidden_tag() }}
              {{ form.file.label }} {{ form.file() }}
              <input type="submit" value="Upload">
            </form>
          </div>
        </div>
      </div>
    </main>
{% endblock %}